server {
    listen 80;
    server_name min-monitoring.ru www.min-monitoring.ru;

    root /srv/production/dist;
    index index.html;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        image/svg+xml;

    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "DENY";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()";

    location / {
        try_files $uri $uri/ /index.html;
    }
    
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/min-monitoring.ru/fullchain.pem; # managed by C>
    ssl_certificate_key /etc/letsencrypt/live/min-monitoring.ru/privkey.pem; # managed by>
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.min-monitoring.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = min-monitoring.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name min-monitoring.ru www.min-monitoring.ru;
    return 404; # managed by Certbot




}
